### PR TITLE
added support for multi-bytes prefixes networks

### PR DESCRIPTION
**Pull request by adrianhdez929**
Attempt to extend the current simple byte implementation of Network support for multiple prefix bytes for other chains with custom address prefixes.

### CODE REVIEW

**Comment by peerchemist** [comment]
Hello, we do not plan to support any other chains but Peercoin. Fork(s) of this library which target any specific altcoin should be relatively easy to maintain if they are also based on Satoshi technology stack.

**Comment by adrianhdez929** [comment]
Nice to know, I thought this would be nice to have, i'll try to keep updated with your repo, but moving for a more flexible variant, thank you so much for making this open source

**Comment by peerchemist** [comment]
Which alternative coin do you plan to support, if I may ask?

**Comment by adrianhdez929** [comment]
I'm primary focusing on Crown, but with a flexible approach to target multiple currencies in the future

**Pull request closed without merging**
